### ISSUE TITLE
10月14日报告

### ISSUE THREAD

**Issue by lengyijun** [sjtu-lyj/finding-phone#3]
关于最近项目进行遇到的一些问题和一些新的想法

新的想法：
1，模仿其他手机寻回，做一个activity校验：就是九宫格解锁之类的。解锁失败就调用前置摄像头拍照并发送
2，内存驻留：找了一份源码，但不知道里面在写什么。慢慢再看
3，向所有联系人发送短信
4，如果系统gps不靠谱，能否调用百度地图或者google地图来截个图发过来？？
5，校验算法能不能用rsa之类的数论算法？？

问题：
1，调用系统gps不稳定。十次尝试九次失败
2，系统的哪一个服务可以稳定的发送图片。qq肯定不行，因为我不知道怎么调用qq发消息
3，小米3，小米4不允许第三方app来拦截短信，也就是说无法即时读取短信（设置里面没有系统短信优先这个选项）。不知道root之后有没有用
4，界面是抄一抄还是自己写：写的肯定不如抄的

已经了解的功能：
1，发短信
2，发出声音，并把声音开到最大（会不会太耗电）
3，监听短信（就是小米有点问题）

**Comment by lengyijun** [comment]
从上文看来，最近做的太少，想的挺多

**Comment by lengyijun** [comment]
大家有什么意见？？

**Comment by maoya667** [comment]
发送gps坐标可以消耗更少能量，不过不便于用户使用。

发自我的 iPhone

**Comment by akiltashi** [comment]
图片可以考虑发送彩信吗？
调用地图是否要求手机必须内置地图软件？如手机无对应软件需如何处理？
或者可否控制打开wifi开关？

**Comment by mayinghua** [comment]
看来，你们对各种功能都有了一定的了解。应该尽快召开plan meeting会议，确定第一轮sprint的工作计划了。 把功能上的思考都写下来，一条条交由团队来讨论，选出最基本的功能（并对这些功能进行细化分解）。

对于功能的开拓可以是无穷无尽的，目前要把聚焦点放在第一步上。第一轮可根据同学的不同情况，安排探针任务（探索某项功能的具体可行性）、学习任务和开发任务。每一位同学都可主动提出自己的学习任务，来配合和跟上整个项目的开发。

**Comment by mayinghua** [comment]
PO在思考问题时，可以按照这样的思路：情景设想。
例如
1，手机在食堂因疏忽遗失：手机在原处，无人捡到；或者被同学捡到，但不知道失主在哪里。
2，手机被小偷偷走，手机关机。。。
3，手机在宿舍某角落里被书埋住了，找不到。

这样容易聚焦。能解决一两个情景就好。
