### ISSUE TITLE
10-23会议总结

### ISSUE THREAD

**Issue by lengyijun** [sjtu-lyj/finding-phone#4]
10-23日在教室花半小时讨论了一下项目

会议结果：
a,项目重新推进。前两周项目有些停顿
b,确定新的计划。在两周内完成一下3个功能的实现：
1，验证算法的实现
2，远程实现锁定，清除数据
3，自动拍照，并通过彩信发送

任务已经分配到个人，临近期中考试，学务繁重。如有延期，到时协商。

**Comment by lengyijun** [comment]
另：请大家有事没事想想还要实现什么功能，随时提出

**Comment by lengyijun** [comment]
我们现在的项目功能还是太单薄了

**Comment by lengyijun** [comment]
我想还是最后的时候做一下单元测试以及apk的逆向，代码混淆之类的

**Comment by mayinghua** [comment]
1，为啥要做逆向？
2，第一轮sprint完成了？验收测试都做了没有?如果完成，再来第二轮sprint。

**Comment by lengyijun** [comment]
计划中的“自动拍照，并通过彩信发送”似乎做不下去了。
主要问题在于如果要用彩信功能没有提供api，所以要调用彩信发图片一定会弹出发送界面，这样就意义不大了
别的手机寻回app都是采用发送到服务器的方式，但我们做不到。
情况就是这样，尚无解决方案

**Comment by mayinghua** [comment]
现在完成的功能有哪些？

**Comment by mayinghua** [comment]
聚焦在第一版demo，完成尽可能少的功能。
我看了一下代码，代码格式比较乱，编码时还请注意随时调整格式。

其他同学是不是在学习android？
学习android，大家可从hello world开始学习一个窗口（Activity）的创建和删除过程。
这个过程算是android的最基础。android系统和其他java不同之处在于：所有的类都是android来管理的，也就是存在随时被消灭的可能，即便是activity，application也是如此。因此，流程上会有一些event需要处理，例如被删除被重建等等。学习从抄代码开始，因为android中有一些规定性的东西，例如有些代码必须在某一个event中处理，因此可先不管为什么，只知道怎么做就好。

**Comment by lengyijun** [comment]
所有代码我们会在最近重新整理一下，顺便加上界面的设计

**Comment by lengyijun** [comment]
有些是抄来的，有些是测试的时候写的，所以比较乱

**Comment by lengyijun** [comment]
暂时只能实现：装上app的手机接收到特定短信的时候发出声音，重设密码锁屏和清除数据

**Comment by mayinghua** [comment]
个人建议，在扩展其他功能之前，可以将这个功能深入下去。
例如说，
如何确定该短信的文本是手机主人所发？是否约定一个密码？或者约定一个计算公式（万一密码忘记）？
